data_path: ./datasets/Planet_Zoo_FBX-smal2/train_q
shape_path: ./datasets/Planet_Zoo_FBX-smal2/train_shape
stats_path: ./datasets/Planet_Zoo_FBX-smal2/stats
output_dir: ./work_dir/train_skeleton_aware_smal33/eval
checkpoint_glob: ./work_dir/train_skeleton_aware_smal33/r2et_skeleton_aware_smal33_ret-*.pt
max_length: 32
min_frames: 32
val_ratio: 0.1
seed: 3047
num_self_samples: 200
num_cross_pairs: 200
device: 0
alpha: 100.0
nu: 100.0
mu: 10.0
euler_ord: yzx
ret_model_args:
  num_joint: 33
  token_channels: 64
  hidden_channels_p: 256
  embed_channels_p: 128
  kp: 0.8
